services:
  app-postgres:
    container_name: graphQLServer-postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - ./env-files/.env-prod-postgres
  postgres:
    image: postgres:14
    container_name: graphQLPostgres
    command: 
      - -p 5432
    expose: 
      - 5432
    env_file:
      - ./env-files/.env-prod-postgres
