services:
  app-memory:
    container_name: graphQLServer-in-memory
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./env-files/.env-prod-memory
