version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: graphQLPostgres
    command: 
      - -p 5432
    expose: 
      - 5432
    env_file:
      - .env-dev
  app:
    container_name: graphQLServer
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env-dev
