// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID            string `json:"id"`
	Comment       string `json:"comment"`
	AuthorID      string `json:"authorId"`
	ItemID        string `json:"itemId"`
	AuthorComment *User  `json:"authorComment"`
}

type CommentResponse struct {
	ID              string             `json:"id"`
	Comment         string             `json:"comment"`
	AuthorID        string             `json:"authorId"`
	PostID          string             `json:"postId"`
	ParentCommentID *string            `json:"parentCommentID,omitempty"`
	AuthorComment   *User              `json:"authorComment"`
	Replies         []*CommentResponse `json:"replies"`
}

type Mutation struct {
}

type Post struct {
	ID          string             `json:"id"`
	Text        string             `json:"text"`
	AuthorID    string             `json:"authorId"`
	AuthorPost  *User              `json:"authorPost"`
	Comments    []*CommentResponse `json:"comments"`
	Commentable bool               `json:"commentable"`
}

type Query struct {
}

type Token struct {
	Token string `json:"token"`
}

type User struct {
	ID       string             `json:"id"`
	Username string             `json:"username"`
	Password string             `json:"password"`
	Posts    []*Post            `json:"posts"`
	Comments []*CommentResponse `json:"comments"`
}
