// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Данные модели служат для валидации данных при обращении клиента к GraphQL серверу

// Модель комментария
type Comment struct {
	ID              string  `json:"id"`
	Comment         string  `json:"comment"`
	AuthorID        string  `json:"authorId"`
	ItemID          string  `json:"itemId"`
}

type CommentResponse struct {
	ID              string  `json:"id"`
	Comment         string  `json:"comment"`
	AuthorID        string  `json:"authorId"`
	PostID          string `json:"postId"`
	ParentCommentID *string `json:"parentCommentId"`
}

type Mutation struct {
}

// Модель поста
type Post struct {
	ID       string `json:"id"`
	Text     string `json:"text"`
	AuthorID string `json:"authorId"`
	Author   *User  `json:"author"`
}

type Query struct {
}

// Модель токена
type Token struct {
	Token string `json:"token"`
}

// Модель пользователя
type User struct {
	ID       string     `json:"id"`
	Username string     `json:"username"`
	Password string     `json:"password"`
	Posts    []*Post    `json:"posts"`
	Comments []*Comment `json:"comments"`
}
